-- CreateTable
CREATE TABLE "PROFILE" (
    "CODPROF" SERIAL NOT NULL,
    "PERFIL" TEXT NOT NULL,
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "DATAINC" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PROFILE_pkey" PRIMARY KEY ("CODPROF")
);

-- CreateTable
CREATE TABLE "USERS" (
    "CODUSU" SERIAL NOT NULL,
    "USUARIO" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "CELULAR" TEXT NOT NULL,
    "DATAINC" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DATAALT" TIMESTAMP(3),
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "CODPROF" INTEGER,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("CODUSU")
);

-- CreateTable
CREATE TABLE "TASKS" (
    "CODTAREFA" SERIAL NOT NULL,
    "TAREFA" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "DATAINC" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DATAALT" TIMESTAMP(3),
    "USUINC" INTEGER,
    "USUALT" INTEGER,
    "STATUS" TEXT NOT NULL,
    "CODUSU" INTEGER,

    CONSTRAINT "TASKS_pkey" PRIMARY KEY ("CODTAREFA")
);

-- CreateTable
CREATE TABLE "TASK_IMAGE" (
    "id" SERIAL NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "CODTAREFA" INTEGER NOT NULL,

    CONSTRAINT "TASK_IMAGE_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "USERS" ADD CONSTRAINT "USERS_CODPROF_fkey" FOREIGN KEY ("CODPROF") REFERENCES "PROFILE"("CODPROF") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TASKS" ADD CONSTRAINT "TASKS_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "USERS"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TASK_IMAGE" ADD CONSTRAINT "TASK_IMAGE_CODTAREFA_fkey" FOREIGN KEY ("CODTAREFA") REFERENCES "TASKS"("CODTAREFA") ON DELETE RESTRICT ON UPDATE CASCADE;
